/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Text, View } from "@aws-amplify/ui-react";
export default function FooterFull(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1440px"
      height="380px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "FooterFull")}
      {...rest}
    >
      <View
        width="1440px"
        height="380px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(242,242,242,1)"
        {...getOverrideProps(overrides, "Background")}
      ></View>
      <Text
        fontFamily="Roboto"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        textTransform="uppercase"
        lineHeight="28.125px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="31.58%"
        bottom="60.79%"
        left="9.38%"
        right="85.35%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Trade"
        {...getOverrideProps(overrides, "Logo")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32.37%"
        bottom="62.37%"
        left="37.15%"
        right="59.38%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Product"
        {...getOverrideProps(overrides, "Subtitle0261")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.21%"
        bottom="50.53%"
        left="37.15%"
        right="59.44%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Product"
        {...getOverrideProps(overrides, "Link0266")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.21%"
        bottom="50.53%"
        left="9.38%"
        right="83.96%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="© 2010 — 2020"
        {...getOverrideProps(overrides, "Copyright")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="52.89%"
        bottom="41.84%"
        left="9.38%"
        right="83.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Privacy — Terms"
        {...getOverrideProps(overrides, "Link0279")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="53.68%"
        bottom="41.05%"
        left="37.15%"
        right="59.44%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Product"
        {...getOverrideProps(overrides, "Link0267")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="63.16%"
        bottom="31.58%"
        left="37.15%"
        right="59.44%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Product"
        {...getOverrideProps(overrides, "Link0268")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.21%"
        bottom="50.53%"
        left="51.04%"
        right="45.69%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Feature"
        {...getOverrideProps(overrides, "Link0269")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="53.68%"
        bottom="41.05%"
        left="51.04%"
        right="45.69%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Feature"
        {...getOverrideProps(overrides, "Link0270")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="63.16%"
        bottom="31.58%"
        left="51.04%"
        right="45.69%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Feature"
        {...getOverrideProps(overrides, "Link0271")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.21%"
        bottom="50.53%"
        left="64.93%"
        right="30.97%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Resource"
        {...getOverrideProps(overrides, "Link0272")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="53.68%"
        bottom="41.05%"
        left="64.93%"
        right="30.97%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Resource"
        {...getOverrideProps(overrides, "Link0273")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="63.16%"
        bottom="31.58%"
        left="64.93%"
        right="30.97%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Resource"
        {...getOverrideProps(overrides, "Link0274")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="44.21%"
        bottom="50.53%"
        left="78.82%"
        right="17.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Company"
        {...getOverrideProps(overrides, "Link0275")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="53.68%"
        bottom="41.05%"
        left="78.82%"
        right="17.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Company"
        {...getOverrideProps(overrides, "Link0276")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="63.16%"
        bottom="31.58%"
        left="78.82%"
        right="17.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Company"
        {...getOverrideProps(overrides, "Link0277")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32.37%"
        bottom="62.37%"
        left="51.04%"
        right="45.14%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Features"
        {...getOverrideProps(overrides, "Subtitle0263")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32.37%"
        bottom="62.37%"
        left="64.93%"
        right="30.42%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Resources"
        {...getOverrideProps(overrides, "Subtitle0264")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="32.37%"
        bottom="62.37%"
        left="78.82%"
        right="17.01%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Company"
        {...getOverrideProps(overrides, "Subtitle0265")}
      ></Text>
    </View>
  );
}
