/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Icon, Text, View } from "@aws-amplify/ui-react";
export default function FooterBlogPost(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1440px"
      height="380px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "FooterBlogPost")}
      {...rest}
    >
      <View
        width="1440px"
        height="380px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(242,242,242,1)"
        {...getOverrideProps(overrides, "Background")}
      ></View>
      <Text
        fontFamily="Roboto"
        fontSize="24px"
        fontWeight="700"
        color="rgba(0,0,0,1)"
        textTransform="uppercase"
        lineHeight="28.125px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="15.53%"
        bottom="76.84%"
        left="9.38%"
        right="85.35%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Trade"
        {...getOverrideProps(overrides, "Logo")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="80.79%"
        bottom="13.95%"
        left="53.75%"
        right="39.58%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="© 2010 — 2020"
        {...getOverrideProps(overrides, "Copyright")}
      ></Text>
      <Text
        fontFamily="Roboto"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="19.6875px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="80.79%"
        bottom="13.95%"
        left="61.53%"
        right="31.32%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Privacy — Terms"
        {...getOverrideProps(overrides, "Link0305")}
      ></Text>
      <Icon
        width="0px"
        height="320px"
        viewBox={{ minX: 0, minY: 0, width: 1, height: 320 }}
        paths={[
          {
            d: "M-0.5 0L-0.5 320L0.5 320L0.5 0L-0.5 0Z",
            stroke: "rgba(0,0,0,1)",
            fillRule: "nonzero",
            strokeWidth: 1,
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="7.89%"
        bottom="7.89%"
        left="50%"
        right="50%"
        {...getOverrideProps(overrides, "Divider")}
      ></Icon>
      <View
        padding="0px 0px 0px 0px"
        width="221px"
        height="174px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="17.89%"
        bottom="36.32%"
        left="53.75%"
        right="30.9%"
        {...getOverrideProps(overrides, "Links Right")}
      >
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="88.51%"
          left="0%"
          right="77.38%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0308")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="24.14%"
          bottom="64.37%"
          left="0%"
          right="77.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0314")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="40.23%"
          bottom="48.28%"
          left="0%"
          right="77.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0315")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="56.32%"
          bottom="32.18%"
          left="0%"
          right="77.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0316")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="72.41%"
          bottom="16.09%"
          left="0%"
          right="77.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0317")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="88.51%"
          bottom="0%"
          left="0%"
          right="77.83%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Product"
          {...getOverrideProps(overrides, "Link0318")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="24.14%"
          bottom="64.37%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0319")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="40.23%"
          bottom="48.28%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0320")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="56.32%"
          bottom="32.18%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0321")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="72.41%"
          bottom="16.09%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0322")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="88.51%"
          bottom="0%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0323")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="88.51%"
          left="72.85%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Company"
          {...getOverrideProps(overrides, "Link0309")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="370px"
        height="158px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="17.89%"
        bottom="40.53%"
        left="20.49%"
        right="53.82%"
        {...getOverrideProps(overrides, "Blog Post")}
      >
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="370px"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="50%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
          {...getOverrideProps(overrides, "Summary")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="22.15%"
          bottom="56.33%"
          left="0%"
          right="38.65%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Ready to get started?"
          {...getOverrideProps(overrides, "Title")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0%"
          bottom="87.34%"
          left="0%"
          right="71.89%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Latest Blog Post"
          {...getOverrideProps(overrides, "Subtitle")}
        ></Text>
      </View>
    </View>
  );
}
