/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Text, View } from "@aws-amplify/ui-react";
export default function PostsBlogLeft(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1440px"
      height="760px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "PostsBlogLeft")}
      {...rest}
    >
      <View
        width="1440px"
        height="760px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(242,242,242,1)"
        {...getOverrideProps(overrides, "Rectangle")}
      ></View>
      <View
        padding="0px 0px 0px 0px"
        width="370px"
        height="600px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="10.53%"
        bottom="10.53%"
        left="9.38%"
        right="64.93%"
        {...getOverrideProps(overrides, "Blog Card Feature")}
      >
        <View
          width="370px"
          height="600px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(0,0,0,1)"
          {...getOverrideProps(overrides, "Background0340")}
        ></View>
        <Text
          fontFamily="Roboto"
          fontSize="56px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="65.625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="410px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="9.33%"
          bottom="22.33%"
          left="12.97%"
          right="12.7%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="The best way to wireframe a website or landing page"
          {...getOverrideProps(overrides, "Title0342")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="370px"
        height="600px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="10.53%"
        bottom="10.53%"
        left="37.15%"
        right="37.15%"
        {...getOverrideProps(overrides, "Blog Card Image")}
      >
        <View
          width="370px"
          height="600px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(136,136,136,1)"
          {...getOverrideProps(overrides, "Background0343")}
        ></View>
        <View
          width="319px"
          height="148px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="15.5%"
          bottom="59.83%"
          left="7.03%"
          right="6.76%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(0,0,0,1)"
          {...getOverrideProps(overrides, "Text Background0346")}
        ></View>
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="101px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="19.5%"
          bottom="63.67%"
          left="13.51%"
          right="12.16%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Keys to writing copy that actually converts and sells users"
          {...getOverrideProps(overrides, "Title0345")}
        ></Text>
        <View
          width="105px"
          height="40px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="6.33%"
          bottom="87%"
          left="7.03%"
          right="64.59%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(0,0,0,1)"
          {...getOverrideProps(overrides, "Text Background0347")}
        ></View>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(255,255,255,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="8.33%"
          bottom="88.33%"
          left="13.51%"
          right="70.81%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Category"
          {...getOverrideProps(overrides, "Subtitle0348")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="370px"
        height="285px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="10.53%"
        bottom="51.97%"
        left="64.93%"
        right="9.38%"
        {...getOverrideProps(overrides, "Blog Card0350")}
      >
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="101px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="41.05%"
          bottom="23.51%"
          left="9.19%"
          right="16.49%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Keys to writing copy that actually converts and sells users"
          {...getOverrideProps(overrides, "Title0351")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(255,255,255,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="17.54%"
          bottom="75.44%"
          left="9.19%"
          right="75.14%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Category"
          {...getOverrideProps(overrides, "Title0352")}
        ></Text>
        <View
          width="370px"
          height="285px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Background0349")}
        ></View>
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="101px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="27.02%"
          bottom="37.54%"
          left="12.7%"
          right="12.97%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Keys to writing copy that actually converts and sells users"
          {...getOverrideProps(overrides, "Title0353")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="18px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="25.3125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="76.49%"
          bottom="14.39%"
          left="12.7%"
          right="59.19%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Author name"
          {...getOverrideProps(overrides, "Author0355")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="14.04%"
          bottom="78.95%"
          left="12.7%"
          right="71.62%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Category"
          {...getOverrideProps(overrides, "Subtitle0354")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="370px"
        height="285px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="51.97%"
        bottom="10.53%"
        left="64.93%"
        right="9.38%"
        {...getOverrideProps(overrides, "Blog Card0376")}
      >
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="101px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="41.05%"
          bottom="23.51%"
          left="9.19%"
          right="16.49%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Keys to writing copy that actually converts and sells users"
          {...getOverrideProps(overrides, "Title0377")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(255,255,255,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="17.54%"
          bottom="75.44%"
          left="9.19%"
          right="75.14%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Category"
          {...getOverrideProps(overrides, "Title0378")}
        ></Text>
        <View
          width="370px"
          height="285px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "Background0379")}
        ></View>
        <Text
          fontFamily="Roboto"
          fontSize="24px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="33.75px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="275px"
          height="101px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="27.02%"
          bottom="37.54%"
          left="12.7%"
          right="12.97%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Keys to writing copy that actually converts and sells users"
          {...getOverrideProps(overrides, "Title0380")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="18px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="25.3125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="76.49%"
          bottom="14.39%"
          left="12.7%"
          right="59.19%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Author name"
          {...getOverrideProps(overrides, "Author0381")}
        ></Text>
        <Text
          fontFamily="Roboto"
          fontSize="14px"
          fontWeight="700"
          color="rgba(0,0,0,1)"
          lineHeight="19.6875px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="14.04%"
          bottom="78.95%"
          left="12.7%"
          right="71.62%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Category"
          {...getOverrideProps(overrides, "Subtitle0382")}
        ></Text>
      </View>
    </View>
  );
}
